// <auto-generated />
namespace RecetAgro_WS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class OverrideProductor_IdToProductorId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(OverrideProductor_IdToProductorId));
        
        string IMigrationMetadata.Id
        {
            get { return "201711130527160_OverrideProductor_IdToProductorId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
